<?xml version="1.0" encoding="utf-8"?><Database Name="LEDExcellence" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Attribute_Category" Member="Attribute_Categories">
    <Type Name="Attribute_Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attribute_Value" Member="Attribute_Values">
    <Type Name="Attribute_Value">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Item_Item_Product" Member="Item_Products" ThisKey="ID" OtherKey="Item_FK" Type="Item_Product" />
      <Association Name="Item_Purchase_Line" Member="Purchase_Lines" ThisKey="ID" OtherKey="Item_FK" Type="Purchase_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Item_Product" Member="Item_Products">
    <Type Name="Item_Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item_FK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_FK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Item_Product" Member="Item" ThisKey="Item_FK" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="Product_Item_Product" Member="Product" ThisKey="Product_FK" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item_SubCategory" Member="Item_SubCategories">
    <Type Name="Item_SubCategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Manufacture_Line" Member="Manufacture_Lines">
    <Type Name="Manufacture_Line">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MO_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ManufactureOrder_Manufacture_Line" Member="ManufactureOrder" ThisKey="MO_FK" OtherKey="ID" Type="ManufactureOrder" IsForeignKey="true" />
      <Association Name="Product_Manufacture_Line" Member="Product" ThisKey="Product_FK" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ManufactureOrder" Member="ManufactureOrders">
    <Type Name="ManufactureOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ManufactureOrder_Manufacture_Line" Member="Manufacture_Lines" ThisKey="ID" OtherKey="MO_FK" Type="Manufacture_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Product_Item_Product" Member="Item_Products" ThisKey="ID" OtherKey="Product_FK" Type="Item_Product" />
      <Association Name="Product_Manufacture_Line" Member="Manufacture_Lines" ThisKey="ID" OtherKey="Product_FK" Type="Manufacture_Line" />
      <Association Name="Product_Sales_Line" Member="Sales_Lines" ThisKey="ID" OtherKey="Product_FK" Type="Sales_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Attribute" Member="Product_Attributes">
    <Type Name="Product_Attribute">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Subcategory" Member="Subcategories">
    <Type Name="Subcategory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SalesOrder" Member="SalesOrders">
    <Type Name="SalesOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SalesOrder_Sales_Line" Member="Sales_Lines" ThisKey="ID" OtherKey="SO_FK" Type="Sales_Line" />
    </Type>
  </Table>
  <Table Name="dbo.Sales_Line" Member="Sales_Lines">
    <Type Name="Sales_Line">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SO_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Sales_Line" Member="Product" ThisKey="Product_FK" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="SalesOrder_Sales_Line" Member="SalesOrder" ThisKey="SO_FK" OtherKey="ID" Type="SalesOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase_Line" Member="Purchase_Lines">
    <Type Name="Purchase_Line">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PO_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Item_Purchase_Line" Member="Item" ThisKey="Item_FK" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="PurchaseOrder_Purchase_Line" Member="PurchaseOrder" ThisKey="PO_FK" OtherKey="ID" Type="PurchaseOrder" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseOrder" Member="PurchaseOrders">
    <Type Name="PurchaseOrder">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PurchaseOrder_Purchase_Line" Member="Purchase_Lines" ThisKey="ID" OtherKey="PO_FK" Type="Purchase_Line" />
    </Type>
  </Table>
</Database>